
ALTER TABLE Benevole DROP CONSTRAINT IF EXISTS fk_benevole_reparation;

DROP TABLE IF EXISTS Reparation;
DROP TABLE IF EXISTS InscriptionAtelierPersonne;
DROP TABLE IF EXISTS Atelier;
DROP TABLE IF EXISTS BenevolePossedeCompetence;
DROP TABLE IF EXISTS BENEVOLE;
DROP TABLE IF EXISTS Objet;
DROP TABLE IF EXISTS Depot;
DROP TABLE IF EXISTS Personne;
DROP TABLE IF EXISTS Competence;
DROP TABLE IF EXISTS Vente;
DROP TABLE IF EXISTS Categorie;
