
DROP TABLE IF EXISTS Reparation CASCADE;
DROP TABLE IF EXISTS InscriptionAtelierPersonne CASCADE;
DROP TABLE IF EXISTS Atelier CASCADE;
DROP TABLE IF EXISTS BenevolePossedeCompetence CASCADE;
DROP TABLE IF EXISTS Benevole CASCADE;
DROP TABLE IF EXISTS Objet CASCADE;
DROP TABLE IF EXISTS Depot CASCADE;
DROP TABLE IF EXISTS Personne CASCADE;
DROP TABLE IF EXISTS Competence CASCADE;
DROP TABLE IF EXISTS Vente CASCADE;
DROP TABLE IF EXISTS Categorie CASCADE;